#!/bin/bash

# ~/.zshrc, ~/.bashrc
SHELL_RC_FILE="$HOME/.$(basename $SHELL)rc"
COUNT=0
IFS=':' read -ra PATHS <<< "$PATH"

for p in "${PATHS[@]}"; do
	if [[ $p == "$HOME/bin" || $p == "~/bin" ]]
	then
		COUNT=$(($COUNT+1))
	fi
done

if [[ $COUNT == 0 ]]
then
	echo 'export PATH=$PATH:$HOME/bin' >> $SHELL_RC_FILE
fi

curl -sSLk -o $HOME/bin/publoy "https://raw.githubusercontent.com/abhiomkar/publoy/master/publoy" && echo -e ">>> Installation successful"
chmod +x $HOME/bin/publoy
