#!/bin/bash
# ~/Dropbox/Public/publoy/.publoy
# [{
# 	project: "save-martian",
# 	source: "~/code/save-martian",
# 	target: "~/Dropbox/Public/publoy/save-martian"
# },
# {
# 	project: "save-martian",
# 	source: "~/Sites/save-martian",
# 	target: "~/Dropbox/Public/publoy/save-martian-1"
# },
# {
# 	project: "save-martian",
# 	source: "~/www/save-martian",
# 	target: "~/Dropbox/Public/publoy/save-martian-2" <-- where '2' is calculated as - count('project:save-martian')
# }]

# ~/code/save-martian $ publoy --> ~/Dropbox/Public/publoy/save-martian
# ~/Sites/save-martian $ publoy --> ~/Dropbox/Public/publoy/save-martian-1
# ~/www/save-martian $ publoy --> ~/Dropbox/Public/publoy/save-martian-2

# check if dropbox is installed
# check if rsync command is available

# create a folder 'publoy' in ~/Dropbox/Public if not exists
# create a new file in the above folder called '.publoy' if not exists
# read .publoy, if project folder path in this file matches with the original project folder then proceed with sync
# if the folder path not found in .publoy file then create a new entry where source: original project path, target: ~/Dropbox/Public/publoy/<project_name>((project_name exists) ? '-$count('project:project_name') : '')
# create a new folder $target
# sync project folder $ rsync -av . $target
# get Dropbox share link of $target


# Good to have
# TODO
# able to clone & sync projects from publoy on other computers

ERROR_STATUS=0

function utime
{
    echo $(date +%s)
}

# create publoy supporting files & folders
DROPBOX_ROOT="$HOME/Dropbox"
if [ ! -d $DROPBOX_ROOT ]
then
    echo "Dropbox is not installed in your system? Exiting."
    ERROR_STATUS=1

    exit $ERROR_STATUS
fi

echo ">>> Publoying..."

PUBLIC_ROOT="$HOME/Dropbox/Public"
[ ! -d $PUBLIC_ROOT ] && mkdir -p $PUBLIC_ROOT
[ ! -d $PUBLOY_ROOT ] && mkdir -p $PUBLOY_ROOT
PUBLOY_ROOT="$HOME/Dropbox/Public/publoy"
PUBLOY_LINKFILE=$PUBLOY_ROOT'/publoy_link'
PUBLOY_METAFILE=$PUBLOY_ROOT'/.publoy'
CONFIG_FILE=$PUBLOY_ROOT'/.publoy_config'
[ ! -d $PUBLOY_ROOT ] && mkdir -p $PUBLOY_ROOT
[ ! -f $PUBLOY_LINKFILE ] && touch $PUBLOY_LINKFILE
[ ! -f $PUBLOY_METAFILE ] && touch $PUBLOY_METAFILE
[ ! -f $CONFIG_FILE ] && touch $CONFIG_FILE

# Info about Project Name, Source & Target - save it to .publoy file if necessary
PROJECT_NAME=$(basename `pwd`)
SOURCE=$(pwd)
PROJECT_NAME_COUNT=0
# TARGET=$PUBLOY_ROOT'/'$PROJECT_NAME

while IFS='' read -r line || [[ -n "$line" ]]; do
    IFS=':' read -ra FIELDS <<< "$line"

    if [ ${FIELDS[0]} == $PROJECT_NAME ]
    then
    	PROJECT_NAME_COUNT=$(($PROJECT_NAME_COUNT+1))
    fi

	for i in "${FIELDS[@]}"; do
		if [ ${FIELDS[1]} == $SOURCE ]
		then
			TARGET=${FIELDS[2]}
		fi
	done
	IFS=''
done < $PUBLOY_METAFILE

if [ -z $TARGET ]
then
	if [ $PROJECT_NAME_COUNT -eq 0 ]
	then
		TARGET_SUFFIX=""
	else
		TARGET_SUFFIX="-$PROJECT_NAME_COUNT"
	fi
	TARGET=$PUBLOY_ROOT'/'$PROJECT_NAME$TARGET_SUFFIX

	echo "$PROJECT_NAME:$SOURCE:$TARGET" >> $PUBLOY_METAFILE
fi

if [ -f "$SOURCE/index.html" ]
then
    INDEX_FILE='index.html'
else
    # if we could'nt find index.html, the first .html file would our index file
    INDEX_FILE=$(find . -type f -maxdepth 1 -iname '*.html' | sed 's/^.\///' | head -n 1)
fi

if [[ $INDEX_FILE == "" ]]
then
    ERROR_STATUS=1

    echo ""
    echo -ne "No 'index.html' file. Exiting."
    echo ""
    exit $ERROR_STATUS
fi

[ ! -d $TARGET ] && mkdir -p $TARGET

echo ">>> Syncing to Dropbox..."

rsync -a --stats . $TARGET > /dev/null && echo ">>> done."

if [ -s $CONFIG_FILE ]
then
    source "$CONFIG_FILE" 2>/dev/null
else
    # first time the user is running the script
    echo -ne "\nThis is the first time you run this script."

    echo -ne "\n\n Please go to $PUBLOY_ROOT folder, right click on publoy_link file, \n"
    echo -ne " click on 'Copy Public Link' and paste it here.\n"
    echo -ne "\nPublic Link: "
    read PUBLIC_LINK

    # Sample Public Link:
    # https://dl.dropboxusercontent.com/u/1234567/publoy/publoy_link
    # now get dropbox user id from PUBLIC_LINK
    re="https:\/\/dl.dropboxusercontent.com\/u\/([0-9]+)\/publoy\/publoy_link"

    if [[ $PUBLIC_LINK =~ $re ]]; then
        uid=${BASH_REMATCH[1]}
        echo "uid=$uid" >> "$CONFIG_FILE"
        echo -ne "> Saved uid in publoy config file.\n"
    else
        echo -ne " FAILED\n"
        ERROR_STATUS=1
    fi
fi

if [ $ERROR_STATUS -eq 0 ]
then
    echo ""
    echo "> Share link: (Syncing...)"
    echo "https://dl.dropboxusercontent.com/u/$uid/publoy/$PROJECT_NAME$TARGET_SUFFIX/$INDEX_FILE"
fi

exit $ERROR_STATUS
